name: resource_hunter
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/lhlyu/resource_hunter

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  encrypt: ^5.0.3
  html: ^0.15.4
  random_user_agents: ^1.0.2
  dio: ^5.5.0+1
  json_path: ^0.7.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  yaml_writer: ^2.0.0
  yaml: ^3.1.2
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

