version: '1723355348339'
platforms: 
  - name: 'cXE='
    label: '6IW+6K6v'
    enable: true
    site: 'aHR0cHM6Ly92LnFxLmNvbQ=='
    tabs: 
      - name: 'dHY='
        label: '55S16KeG5Ymn'
      - name: 'bW92aWU='
        label: '55S15b2x'
      - name: 'Y2FydG9vbg=='
        label: '5Yqo5ryr'
    viewer: 'cXE='
    querier: 'cXE='
    searcher: 'cXE='
    parser: 'Z2VuZXJhbA=='
  - name: 'aXFpeWk='
    label: '54ix5aWH6Im6'
    enable: true
    site: 'aHR0cHM6Ly93d3cuaXFpeWkuY29t'
    tabs: 
      - name: 'dHY='
        label: '55S16KeG5Ymn'
      - name: 'bW92aWU='
        label: '55S15b2x'
      - name: 'Y2FydG9vbg=='
        label: '5Yqo5ryr'
    viewer: 'aXFpeWk='
    querier: 'aXFpeWk='
    searcher: 'aXFpeWk='
    parser: 'Z2VuZXJhbA=='
  - name: 'eW91a3U='
    label: '5LyY6YW3'
    enable: true
    site: 'aHR0cHM6Ly95b3VrdS5jb20='
    tabs: 
      - name: 'dHY='
        label: '55S16KeG5Ymn'
      - name: 'bW92aWU='
        label: '55S15b2x'
      - name: 'Y2FydG9vbg=='
        label: '5Yqo5ryr'
    viewer: 'eW91a3U='
    querier: 'eW91a3U='
    searcher: 'eW91a3U='
    parser: 'Z2VuZXJhbA=='
  - name: 'bWd0dg=='
    label: '6IqS5p6c'
    enable: true
    site: 'aHR0cHM6Ly93d3cubWd0di5jb20='
    tabs: 
      - name: 'dHY='
        label: '55S16KeG5Ymn'
      - name: 'bW92aWU='
        label: '55S15b2x'
      - name: 'Y2FydG9vbg=='
        label: '5Yqo5ryr'
    viewer: 'bWd0dg=='
    querier: 'bWd0dg=='
    searcher: 'bWd0dg=='
    parser: 'Z2VuZXJhbA=='
  - name: 'YmlsaWJpbGk='
    label: 'QuermQ=='
    enable: true
    site: 'aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29t'
    tabs: 
      - name: 'dmlkZW8='
        label: '5o6o6I2Q'
      - name: 'YW5pbWU='
        label: '55Wq5Ymn'
    viewer: 'YmlsaWJpbGk='
    querier: 'YmlsaWJpbGk='
    searcher: 'YmlsaWJpbGk='
    parser: 'Z2VuZXJhbA=='
